services:
  redis:
    image: redis:latest
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - ualanet

networks:
  ualanet:
    driver: bridge

volumes:
  redis-data:
    driver: local